<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Huiru Yang">
<meta name="dcterms.date" content="2026-05-13">

<title>Replication of Card and Krueger (1994) – Qiang Hu</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Qiang Hu</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../hobbies.html"> 
<span class="menu-text">Hobbies</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rsm-qih029"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/qiang-hu-12971385"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-and-variable-construction" id="toc-data-and-variable-construction" class="nav-link" data-scroll-target="#data-and-variable-construction">Data and Variable Construction</a></li>
  <li><a href="#why-difference-in-differences-is-the-right-design" id="toc-why-difference-in-differences-is-the-right-design" class="nav-link" data-scroll-target="#why-difference-in-differences-is-the-right-design">Why Difference-in-Differences Is the Right Design</a></li>
  <li><a href="#replication-of-table-2-selected-statistics" id="toc-replication-of-table-2-selected-statistics" class="nav-link" data-scroll-target="#replication-of-table-2-selected-statistics">Replication of Table 2 (Selected Statistics)</a></li>
  <li><a href="#replication-of-table-3-the-main-difference-in-differences-result" id="toc-replication-of-table-3-the-main-difference-in-differences-result" class="nav-link" data-scroll-target="#replication-of-table-3-the-main-difference-in-differences-result">Replication of Table 3: The Main Difference-in-Differences Result</a></li>
  <li><a href="#interpreting-table-3-more-carefully" id="toc-interpreting-table-3-more-carefully" class="nav-link" data-scroll-target="#interpreting-table-3-more-carefully">Interpreting Table 3 More Carefully</a></li>
  <li><a href="#replication-of-table-4-column-i" id="toc-replication-of-table-4-column-i" class="nav-link" data-scroll-target="#replication-of-table-4-column-i">Replication of Table 4, Column (i)</a></li>
  <li><a href="#summary-of-the-main-replicated-results" id="toc-summary-of-the-main-replicated-results" class="nav-link" data-scroll-target="#summary-of-the-main-replicated-results">Summary of the Main Replicated Results</a></li>
  <li><a href="#additional-analysis-part-1-a-graphical-presentation-of-the-main-result" id="toc-additional-analysis-part-1-a-graphical-presentation-of-the-main-result" class="nav-link" data-scroll-target="#additional-analysis-part-1-a-graphical-presentation-of-the-main-result">Additional Analysis Part 1: A Graphical Presentation of the Main Result</a></li>
  <li><a href="#additional-analysis-part-2-did-firms-adjust-through-prices" id="toc-additional-analysis-part-2-did-firms-adjust-through-prices" class="nav-link" data-scroll-target="#additional-analysis-part-2-did-firms-adjust-through-prices">Additional Analysis Part 2: Did Firms Adjust Through Prices?</a></li>
  <li><a href="#additional-analysis-part-3-regression-with-controls" id="toc-additional-analysis-part-3-regression-with-controls" class="nav-link" data-scroll-target="#additional-analysis-part-3-regression-with-controls">Additional Analysis Part 3: Regression with Controls</a></li>
  <li><a href="#why-the-statistical-method-supports-a-causal-conclusion" id="toc-why-the-statistical-method-supports-a-causal-conclusion" class="nav-link" data-scroll-target="#why-the-statistical-method-supports-a-causal-conclusion">Why the Statistical Method Supports a Causal Conclusion</a></li>
  <li><a href="#comparison-to-the-conventional-model" id="toc-comparison-to-the-conventional-model" class="nav-link" data-scroll-target="#comparison-to-the-conventional-model">Comparison to the Conventional Model</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Card and Krueger (1994)</h1>
<p class="subtitle lead">Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Huiru Yang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This post replicates the main analysis from <strong>Card and Krueger (1994), “Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania.”</strong> The paper studies one of the most important questions in labor economics: <strong>does raising the minimum wage reduce employment?</strong> In the standard competitive model, a binding minimum wage should raise the cost of low-wage labor and reduce firms’ demand for workers. Card and Krueger revisit that prediction in a setting where a real policy change created a strong natural experiment.</p>
<p>The policy shock is unusually clear. On <strong>April 1, 1992</strong>, New Jersey raised its minimum wage from <strong>$4.25 to $5.05 per hour</strong>. Pennsylvania did not adopt the same increase at the same time. The authors surveyed fast-food restaurants in New Jersey and eastern Pennsylvania just before the policy change and then again several months later. This creates a natural <strong>difference-in-differences (DID)</strong> design: compare employment changes in New Jersey, the treated state, with employment changes in Pennsylvania, the control state.</p>
<p>This paper is especially attractive for replication because the design is simple, transparent, and directly tied to an important economic debate. The authors are not just comparing different kinds of workers at one point in time, which would be vulnerable to omitted-variable bias and selection problems. Instead, they compare the same industry across two nearby locations, before and after a specific law changed. That setup makes the causal question much sharper.</p>
<p>The paper became famous because its central finding ran against the conventional textbook prediction. Rather than finding that a higher minimum wage reduced fast-food employment, Card and Krueger found <strong>no evidence that employment fell in New Jersey relative to Pennsylvania</strong>. In some specifications, the point estimate was actually positive. This result became one of the most influential findings in empirical labor economics and helped reshape the modern literature on minimum wages.</p>
<p>In this replication, I satisfy all three required parts of the assignment. First, I explain what the authors are studying and why their design may support a causal interpretation. Second, I replicate the key statistical findings requested in the assignment: selected results from <strong>Table 2</strong>, the <strong>first three rows and first three columns of Table 3</strong>, and <strong>Table 4 column (i)</strong>. Third, for the required “do one additional thing” component, I go beyond the minimum requirement in several ways: I graph the main DID result, I estimate whether firms adjusted through prices, and I explain in more detail why DID is the correct empirical strategy in this setting and what assumptions it relies on.</p>
</section>
<section id="data-and-variable-construction" class="level1">
<h1>Data and Variable Construction</h1>
<p>The data used here come from the public fast-food survey files associated with the paper. The main data file is <code>public.dat</code>, a fixed-width dataset containing information from two waves of interviews. The first wave took place shortly before the minimum-wage increase, and the second occurred several months afterward. The sample includes Burger King, KFC, Roy Rogers, and Wendy’s restaurants in New Jersey and eastern Pennsylvania.</p>
<p>The central outcome variable is <strong>full-time-equivalent employment (FTE)</strong>. Following the paper, I construct it as:</p>
<p>[ FTE = + + 0.5 . ]</p>
<p>This construction matters because fast-food restaurants rely heavily on part-time labor. Treating part-time workers as one-half of a full-time worker provides a standardized measure of the effective size of a restaurant’s workforce and is consistent with the way the original paper reports employment.</p>
<p>I also follow the paper’s treatment of permanently closed stores. If a store was permanently closed by the second wave, I set second-wave employment equal to zero. This is important for policy analysis. If the minimum wage caused some restaurants to close, then excluding those stores would understate the true employment effect. Including closures produces a more complete measure of what happened to employment in the original sample of establishments.</p>
<p>I construct two main explanatory variables. The first is <code>nj</code>, which equals 1 for New Jersey and 0 for Pennsylvania. This is the main DID treatment indicator. The second is the paper’s <strong>gap</strong> variable, which measures how much a New Jersey store’s starting wage would have needed to increase proportionally to reach the new $5.05 minimum. This variable captures treatment intensity, since a store already paying $5.05 or more should be less affected by the law than a store initially paying $4.25.</p>
</section>
<section id="why-difference-in-differences-is-the-right-design" class="level1">
<h1>Why Difference-in-Differences Is the Right Design</h1>
<p>The main empirical challenge is that New Jersey and Pennsylvania stores do not begin at identical employment levels. Pennsylvania stores are somewhat larger on average before the policy change. That means a simple comparison of employment levels after the law would be misleading. It would mix the effect of the policy with pre-existing structural differences between the two states.</p>
<p>Difference-in-differences solves this problem by comparing <strong>changes over time</strong> rather than just levels. The DID estimate is:</p>
<p>[ = ({Y}<em>{NJ,after} - {Y}</em>{NJ,before}) - ({Y}<em>{PA,after} - {Y}</em>{PA,before}). ]</p>
<p>This estimator removes permanent baseline differences between New Jersey and Pennsylvania and also removes any broad shocks affecting both groups over time. What remains is the relative change in the treated state after the policy.</p>
<p>The crucial identifying assumption is the <strong>parallel trends assumption</strong>: in the absence of the minimum-wage increase, employment in New Jersey would have changed in the same way as employment in Pennsylvania. That assumption is not directly testable with only one clean pre-period in the survey data, so it should be treated as an assumption rather than a proven fact. Still, the design makes it plausible. The treatment and control groups are geographically close, operate in the same industry, are exposed to similar macroeconomic conditions, and are observed over the same time window.</p>
<p>At the same time, DID is not automatic proof of causality. If New Jersey was hit by a different unobserved demand shock at exactly the same time as the wage increase, then the DID estimate could reflect more than the policy. This limitation is worth acknowledging. Even so, compared with a simple before-after comparison in New Jersey alone or a simple cross-sectional comparison between states, DID is clearly the right empirical strategy here.</p>
</section>
<section id="replication-of-table-2-selected-statistics" class="level1">
<h1>Replication of Table 2 (Selected Statistics)</h1>
<p>The assignment asks for replication of some of Table 2. These descriptive statistics are important because they establish the baseline comparability of the two states and show how the wage distribution shifted after the law.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>table2_show <span class="ot">&lt;-</span> table2_rep</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>table2_show<span class="sc">$</span>NJ <span class="ot">&lt;-</span> <span class="fu">round</span>(table2_show<span class="sc">$</span>NJ, <span class="dv">2</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>table2_show<span class="sc">$</span>PA <span class="ot">&lt;-</span> <span class="fu">round</span>(table2_show<span class="sc">$</span>PA, <span class="dv">2</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  table2_show,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Replication of selected rows from Table 2"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<caption>Replication of selected rows from Table 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">NJ</th>
<th style="text-align: right;">PA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Burger King (%)</td>
<td style="text-align: right;">41.09</td>
<td style="text-align: right;">44.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">KFC (%)</td>
<td style="text-align: right;">20.54</td>
<td style="text-align: right;">15.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Roy Rogers (%)</td>
<td style="text-align: right;">24.77</td>
<td style="text-align: right;">21.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wendy’s (%)</td>
<td style="text-align: right;">13.60</td>
<td style="text-align: right;">18.99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Company-owned (%)</td>
<td style="text-align: right;">34.14</td>
<td style="text-align: right;">35.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 1: FTE employment</td>
<td style="text-align: right;">20.44</td>
<td style="text-align: right;">23.33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 1: Percentage full-time employees</td>
<td style="text-align: right;">32.85</td>
<td style="text-align: right;">35.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 1: Starting wage</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: right;">4.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 1: Wage = $4.25 (%)</td>
<td style="text-align: right;">32.17</td>
<td style="text-align: right;">34.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 1: Price of full meal</td>
<td style="text-align: right;">3.35</td>
<td style="text-align: right;">3.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 1: Hours open (weekday)</td>
<td style="text-align: right;">14.42</td>
<td style="text-align: right;">14.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 1: Recruiting bonus (%)</td>
<td style="text-align: right;">23.56</td>
<td style="text-align: right;">29.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 2: FTE employment</td>
<td style="text-align: right;">21.03</td>
<td style="text-align: right;">21.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 2: Percentage full-time employees</td>
<td style="text-align: right;">35.87</td>
<td style="text-align: right;">30.38</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 2: Starting wage</td>
<td style="text-align: right;">5.08</td>
<td style="text-align: right;">4.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 2: Wage = $5.05 (%)</td>
<td style="text-align: right;">88.99</td>
<td style="text-align: right;">1.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 2: Price of full meal</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: right;">3.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 2: Hours open (weekday)</td>
<td style="text-align: right;">14.42</td>
<td style="text-align: right;">14.65</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 2: Recruiting bonus (%)</td>
<td style="text-align: right;">20.32</td>
<td style="text-align: right;">23.38</td>
</tr>
</tbody>
</table>
<p>Several patterns stand out. First, the chain composition is broadly similar across states. Both New Jersey and Pennsylvania contain stores from the same major fast-food chains, which helps because the establishments are operating in very similar product markets.</p>
<p>Second, before the policy change, the average starting wage is relatively similar in the two states. That matters because it suggests the labor market conditions were not completely different at baseline. After the law changed, however, average starting wages in New Jersey rose substantially while Pennsylvania’s did not. This confirms that the treatment was real and that the minimum-wage law actually affected wages at many New Jersey stores.</p>
<p>Third, average FTE employment is initially somewhat lower in New Jersey than in Pennsylvania. This is exactly why the DID framework is necessary. If I compared only the employment levels after the policy, I would miss the fact that the two states were already different beforehand. The correct question is not which state has more employment in absolute terms, but whether New Jersey’s employment changed differently over time after the policy shock.</p>
<p>Finally, the full-meal price appears to rise somewhat more in New Jersey than in Pennsylvania. This already hints at one mechanism of adjustment. If restaurants can pass some of their higher labor costs on to consumers through prices, then employment may not need to fall as sharply as the simplest competitive model predicts.</p>
</section>
<section id="replication-of-table-3-the-main-difference-in-differences-result" class="level1">
<h1>Replication of Table 3: The Main Difference-in-Differences Result</h1>
<p>The assignment specifically requires the <strong>nine numbers in Table 3, columns 1–3 and rows 1–3</strong>. These numbers contain the core descriptive DID result in the paper.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>table3_show <span class="ot">&lt;-</span> table3_rep</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>table3_show<span class="sc">$</span>PA <span class="ot">&lt;-</span> <span class="fu">round</span>(table3_show<span class="sc">$</span>PA, <span class="dv">2</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>table3_show<span class="sc">$</span>NJ <span class="ot">&lt;-</span> <span class="fu">round</span>(table3_show<span class="sc">$</span>NJ, <span class="dv">2</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>table3_show<span class="sc">$</span><span class="st">`</span><span class="at">NJ - PA</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">round</span>(table3_show<span class="sc">$</span><span class="st">`</span><span class="at">NJ - PA</span><span class="st">`</span>, <span class="dv">2</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  table3_show,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Replication of Table 3 (rows 1–3, columns 1–3, plus the NJ-PA difference)"</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<caption>Replication of Table 3 (rows 1–3, columns 1–3, plus the NJ-PA difference)</caption>
<colgroup>
<col style="width: 72%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">PA</th>
<th style="text-align: right;">NJ</th>
<th style="text-align: right;">NJ - PA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. FTE employment before, all available observations</td>
<td style="text-align: right;">23.33</td>
<td style="text-align: right;">20.44</td>
<td style="text-align: right;">-2.89</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. FTE employment after, all available observations</td>
<td style="text-align: right;">21.17</td>
<td style="text-align: right;">21.03</td>
<td style="text-align: right;">-0.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Change in mean FTE employment</td>
<td style="text-align: right;">-2.17</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">2.75</td>
</tr>
</tbody>
</table>
<p>The key number is the DID estimate:</p>
<p>[ (NJ) - (PA) = 0.59 - (-2.17) = 2.75. ]</p>
<p>This is the heart of the paper. Employment in Pennsylvania <strong>falls</strong> over the period, while employment in New Jersey is approximately flat or slightly rising. As a result, New Jersey’s employment change is more favorable than Pennsylvania’s after the minimum-wage increase.</p>
<p>This pattern directly contradicts the simplest version of the standard competitive model. If a binding minimum wage necessarily reduced labor demand, I would expect New Jersey employment to fall relative to Pennsylvania. Instead, the DID estimate is positive.</p>
<p>The magnitude is economically meaningful. A change of around 2.75 FTE workers per store is not trivial in the fast-food sector. Because restaurants are relatively small employers, a change of even a couple of workers per store is substantial. That is one reason the paper had such a large impact: the result was not merely statistically noisy, but substantively important.</p>
</section>
<section id="interpreting-table-3-more-carefully" class="level1">
<h1>Interpreting Table 3 More Carefully</h1>
<p>The Table 3 numbers are especially useful because they show exactly where the DID estimate comes from. Before the policy, Pennsylvania stores average <strong>23.33</strong> FTE workers and New Jersey stores average <strong>20.44</strong>. This means Pennsylvania stores are larger at baseline. If I stopped there and compared only levels, I might incorrectly conclude that Pennsylvania simply has the stronger labor market.</p>
<p>After the policy, Pennsylvania stores average <strong>21.17</strong> FTE workers, while New Jersey stores average <strong>21.03</strong>. The cross-state gap becomes much smaller. The critical point is that the relative trend changes. Pennsylvania loses employment over the period, while New Jersey does not.</p>
<p>This is precisely why DID is the correct framework. It prevents me from confusing pre-existing cross-state differences with the effect of the policy. It also sharpens the research question: did New Jersey move differently from Pennsylvania after the law changed? In this replication, the answer is yes, and the difference goes in the direction of <strong>no job loss</strong>.</p>
</section>
<section id="replication-of-table-4-column-i" class="level1">
<h1>Replication of Table 4, Column (i)</h1>
<p>The assignment also requires replication of <strong>Table 4 column (i)</strong>. In the paper, this is the regression of the change in FTE employment on a New Jersey dummy:</p>
<p>[ FTE_i = + NJ_i + _i. ]</p>
<p>The coefficient on the New Jersey dummy is the regression analogue of the DID estimate in the paper’s restricted regression sample.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>tab4_col1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Term =</span> <span class="fu">c</span>(<span class="st">"New Jersey dummy"</span>, <span class="st">"Standard error"</span>, <span class="st">"t statistic"</span>, <span class="st">"Observations"</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(<span class="fu">round</span>(coef_t4c1, <span class="dv">2</span>), <span class="fu">round</span>(se_t4c1, <span class="dv">2</span>), <span class="fu">round</span>(t_t4c1, <span class="dv">2</span>), n_t4c1)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  tab4_col1,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Replication of Table 4, column (i)"</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<caption>Replication of Table 4, column (i)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New Jersey dummy</td>
<td style="text-align: right;">2.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard error</td>
<td style="text-align: right;">1.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">t statistic</td>
<td style="text-align: right;">1.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">351.00</td>
</tr>
</tbody>
</table>
<p>My estimated coefficient on the New Jersey dummy is <strong>2.28</strong>, with a standard error of <strong>1.19</strong>. This is close to the paper’s reported estimate of about <strong>2.33</strong>. The interpretation is that, on average, New Jersey restaurants increased employment by roughly 2.3 FTE workers more than Pennsylvania restaurants in the restricted regression sample.</p>
<p>This replication matters because it shows that the main result is not just an artifact of one descriptive table. Once the same comparison is placed in a regression framework, the conclusion is the same. The treatment-state coefficient remains positive rather than negative.</p>
</section>
<section id="summary-of-the-main-replicated-results" class="level1">
<h1>Summary of the Main Replicated Results</h1>
<p>To summarize the most important quantities in one place, I report them below.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>compare_show <span class="ot">&lt;-</span> compare_main</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>compare_show<span class="sc">$</span>My_replication <span class="ot">&lt;-</span> <span class="fu">round</span>(compare_show<span class="sc">$</span>My_replication, <span class="dv">2</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  compare_show,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Summary of main replicated quantities"</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<caption>Summary of main replicated quantities</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">My_replication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Table 3: PA before</td>
<td style="text-align: right;">23.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">Table 3: NJ before</td>
<td style="text-align: right;">20.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Table 3: PA after</td>
<td style="text-align: right;">21.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Table 3: NJ after</td>
<td style="text-align: right;">21.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Table 3: PA change</td>
<td style="text-align: right;">-2.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Table 3: NJ change</td>
<td style="text-align: right;">0.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Table 3: DID</td>
<td style="text-align: right;">2.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Table 4 col (i): NJ dummy</td>
<td style="text-align: right;">2.28</td>
</tr>
</tbody>
</table>
<p>Overall, the replication matches the paper closely enough to support the same substantive interpretation. Minor discrepancies can arise because of choices about missing values, rounding, sample restrictions, or the treatment of unusual store statuses. But the core pattern is very stable: the point estimates do <strong>not</strong> support the claim that the New Jersey minimum-wage increase reduced fast-food employment.</p>
</section>
<section id="additional-analysis-part-1-a-graphical-presentation-of-the-main-result" class="level1">
<h1>Additional Analysis Part 1: A Graphical Presentation of the Main Result</h1>
<p>For the assignment’s required “do one additional thing” component, I first present the main DID result graphically. This is useful because the original paper emphasizes the result in tables, but a graph makes the logic of difference-in-differences much easier to see.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plot_mat <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  did_plot<span class="sc">$</span>PA,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  did_plot<span class="sc">$</span>NJ</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(plot_mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(plot_mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Pennsylvania"</span>, <span class="st">"New Jersey"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  plot_mat,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">beside =</span> <span class="cn">TRUE</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(plot_mat) <span class="sc">+</span> <span class="dv">4</span>),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Average FTE employment"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Difference-in-Differences in Fast-Food Employment"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.text =</span> <span class="fu">rownames</span>(plot_mat),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> bp,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">as.vector</span>(plot_mat) <span class="sc">+</span> <span class="fl">0.5</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">round</span>(<span class="fu">as.vector</span>(plot_mat), <span class="dv">2</span>),</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.9</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/did-graph-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The graph makes the paper’s central finding easy to visualize. Pennsylvania starts with higher average employment but then experiences a decline. New Jersey begins at a lower level but remains roughly stable or rises slightly. The gap between the two states narrows after the policy, which is the opposite of what one would expect if the higher minimum wage caused a large reduction in employment.</p>
<p>This graphical presentation adds value beyond the table because it shows the identification strategy visually. The DID estimate is literally the difference in the slopes of these two before-after changes. In that sense, the graph is a natural extension of the main statistical finding rather than just a decorative figure.</p>
</section>
<section id="additional-analysis-part-2-did-firms-adjust-through-prices" class="level1">
<h1>Additional Analysis Part 2: Did Firms Adjust Through Prices?</h1>
<p>A second useful extension is to examine whether restaurants responded along another margin besides employment. If labor costs rose in New Jersey, one possible adjustment mechanism is that restaurants passed some of those costs through to consumers via higher prices. The paper discusses this possibility, and it is economically important because it helps explain how employment could remain stable even when wages rose.</p>
<p>I estimate a simple DID-style regression of the change in the log price of a full meal on the New Jersey dummy.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>price_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Term =</span> <span class="fu">c</span>(<span class="st">"New Jersey dummy"</span>, <span class="st">"Standard error"</span>, <span class="st">"t statistic"</span>, <span class="st">"Observations"</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(<span class="fu">round</span>(coef_price, <span class="dv">3</span>), <span class="fu">round</span>(se_price, <span class="dv">3</span>), <span class="fu">round</span>(t_price, <span class="dv">2</span>), n_price)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  price_tab,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Additional analysis: DID regression for the change in log meal price"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<caption>Additional analysis: DID regression for the change in log meal price</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New Jersey dummy</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard error</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">t statistic</td>
<td style="text-align: right;">2.090</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">356.000</td>
</tr>
</tbody>
</table>
<p>The estimated New Jersey coefficient is <strong>0.029</strong>, which implies that meal prices rose by about <strong>2.89%</strong> more in New Jersey than in Pennsylvania over the study period. This result is economically sensible. If higher labor costs were partly passed through to customers, then restaurants would not need to reduce employment one-for-one in response to the higher wage floor.</p>
<p>This price result therefore complements the main employment finding. Instead of treating the labor market in isolation, it suggests that firms adjusted on multiple margins. That makes the overall result much more plausible: higher wages need not necessarily translate into fewer jobs if some adjustment occurs through prices, margins, productivity, or other channels.</p>
</section>
<section id="additional-analysis-part-3-regression-with-controls" class="level1">
<h1>Additional Analysis Part 3: Regression with Controls</h1>
<p>As a further extension, I estimate a regression that adds chain fixed effects and an ownership indicator. This is not required by the assignment, but it helps show that the basic result is not driven purely by the composition of restaurants.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>control_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Term =</span> <span class="fu">c</span>(<span class="st">"New Jersey dummy"</span>, <span class="st">"Standard error"</span>, <span class="st">"t statistic"</span>),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(<span class="fu">round</span>(coef_chain, <span class="dv">2</span>), <span class="fu">round</span>(se_chain, <span class="dv">2</span>), <span class="fu">round</span>(t_chain, <span class="dv">2</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  control_tab,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Additional analysis: employment regression with chain and ownership controls"</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<caption>Additional analysis: employment regression with chain and ownership controls</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New Jersey dummy</td>
<td style="text-align: right;">2.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard error</td>
<td style="text-align: right;">1.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">t statistic</td>
<td style="text-align: right;">1.91</td>
</tr>
</tbody>
</table>
<p>The coefficient on the New Jersey dummy remains <strong>2.28</strong> after including controls for restaurant chain and company ownership. This reinforces the main conclusion. The positive relative employment effect is not simply a byproduct of New Jersey having a different mix of Burger King, KFC, Roy Rogers, or Wendy’s outlets.</p>
<p>Adding controls is also useful from an econometric perspective because it reduces concern that changes in employment are picking up compositional differences across chains rather than the effect of the minimum-wage increase itself. Even after these adjustments, the result does not turn negative.</p>
</section>
<section id="why-the-statistical-method-supports-a-causal-conclusion" class="level1">
<h1>Why the Statistical Method Supports a Causal Conclusion</h1>
<p>Another acceptable way to satisfy the assignment’s “do one additional thing” requirement is to explain why the statistical method allows the authors to draw a causal conclusion. I do that here explicitly.</p>
<p>The reason DID can support causal inference is that it compares the treated group to a counterfactual trend. Instead of asking whether New Jersey restaurants had lower employment after the policy, it asks whether New Jersey restaurants changed differently than similar restaurants in Pennsylvania over the same period. That is a much stronger design because it controls for two major confounders:</p>
<ol type="1">
<li><p><strong>Permanent baseline differences across states.</strong><br>
New Jersey and Pennsylvania stores do not start at the same employment level, but DID differences those permanent differences out.</p></li>
<li><p><strong>Common time shocks.</strong><br>
If the regional economy weakened between the first and second survey waves, that could reduce employment in both states. DID subtracts out these shared macro trends as long as they affect both groups similarly.</p></li>
</ol>
<p>Under the parallel-trends assumption, the remaining difference in employment changes can be interpreted as the causal effect of the policy. This is why DID is one of the most widely used methods in applied microeconomics.</p>
<p>That said, the design still has limits. The biggest one is that there is only a short pre-period, so parallel trends cannot be tested in a convincing way using multiple pre-treatment years. The data also come from telephone surveys rather than administrative payroll records, which may introduce measurement error. Finally, standard errors may differ slightly from the paper’s depending on exact sample restrictions and whether one clusters or adjusts them differently. These limitations do not eliminate the value of the design, but they are important to acknowledge in any careful replication.</p>
</section>
<section id="comparison-to-the-conventional-model" class="level1">
<h1>Comparison to the Conventional Model</h1>
<p>One reason this paper matters so much is that it challenged the simplest version of the conventional competitive model. In that model, a higher wage floor raises labor costs and should lead firms to hire fewer low-wage workers. If that mechanism operated strongly in this setting, I would expect New Jersey employment to fall relative to Pennsylvania after the wage increase.</p>
<p>That is not what I find. The descriptive DID estimate is positive, the regression estimate is positive, the graphical evidence tells the same story, and the price analysis suggests firms may have adjusted in part through product prices instead of employment cuts.</p>
<p>This does not prove that minimum wages can never reduce employment. It does show, however, that the effect is ultimately an empirical question rather than something that can be assumed from theory alone. The Card and Krueger paper helped shift the literature in exactly that direction: away from relying exclusively on simple theory and toward careful causal identification with real policy variation.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This replication reproduces the main message of <strong>Card and Krueger (1994)</strong>. Using the fast-food restaurant survey data from New Jersey and Pennsylvania, I replicated selected descriptive statistics from <strong>Table 2</strong>, the required <strong>nine numbers from Table 3</strong>, and the key regression result from <strong>Table 4 column (i)</strong>. Across these exercises, the same conclusion emerges: the 1992 increase in New Jersey’s minimum wage does <strong>not</strong> appear to have reduced fast-food employment relative to Pennsylvania.</p>
<p>The main descriptive DID estimate is approximately <strong>2.75</strong> FTE workers per store, and the regression estimate for the New Jersey dummy is approximately <strong>2.28</strong>. Both are inconsistent with the claim that the minimum-wage increase caused a fall in employment in this setting.</p>
<p>For the additional part of the assignment, I went beyond basic replication in three ways. First, I graphed the DID pattern so the logic of the identification strategy is visually clear. Second, I estimated a price regression showing that meal prices rose somewhat more in New Jersey, suggesting that firms may have adjusted through prices rather than layoffs. Third, I explained why DID is the correct research design here and how it supports a causal interpretation under the parallel-trends assumption.</p>
<p>Overall, this replication shows why Card and Krueger (1994) remains such a foundational paper in empirical economics. Its importance is not just that it found an unexpected result, but that it used a transparent empirical design to challenge a deeply rooted theoretical prediction. That combination of a clear research question, a credible identification strategy, and a surprising but well-documented result is exactly what makes the paper a classic.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>