<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Qiang Hu">
<meta name="dcterms.date" content="2026-04-25">

<title>Replication of Card and Krueger (1994) – Qiang Hu</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Qiang Hu</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../hobbies.html"> 
<span class="menu-text">Hobbies</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rsm-qih029"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/qiang-hu-12971385"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Card and Krueger (1994)</h1>
<p class="subtitle lead">Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Qiang Hu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>David Card and Alan Krueger (1994) study one of the most important questions in labor economics: does raising the minimum wage reduce employment? Their paper examines a natural policy experiment. On April 1, 1992, New Jersey increased its minimum wage from $4.25 to $5.05, while neighboring eastern Pennsylvania did not change its minimum wage during the same period. This setting makes it possible to compare employment changes across two nearby labor markets facing different policy environments.</p>
<p>The paper focuses on fast-food restaurants, a sector in which many workers earn relatively low wages and where the minimum wage should therefore matter the most. Under the standard competitive model, a higher wage floor should reduce employment. Card and Krueger revisit that prediction using data from fast-food stores in New Jersey and Pennsylvania before and after the policy change.</p>
<p>The empirical strategy is a classic difference-in-differences design. Instead of only comparing New Jersey before and after the increase, the paper also compares the contemporaneous change in Pennsylvania. This matters because employment could change over time for many reasons unrelated to the policy itself, such as regional macroeconomic conditions, industry demand shifts, or seasonal fluctuations. By subtracting the Pennsylvania change from the New Jersey change, the difference-in-differences estimate aims to isolate the effect of the minimum-wage increase.</p>
<p>In this post, I replicate selected findings from the public replication files. Specifically, I reproduce selected descriptive statistics from Table 2, the 9 requested numbers from Table 3 (rows 1–3 and columns 1–3), and Table 4 column (i). As an additional analysis, I also graph the employment changes and explain why the difference-in-differences design supports a causal interpretation.</p>
</section>
<section id="main-analysis" class="level2">
<h2 class="anchored" data-anchor-id="main-analysis">Main Analysis</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>The replication files include a flat data file, <code>public.dat</code>, along with a codebook and the original <code>check.sas</code> program. The main data set contains 410 fast-food restaurants. Each observation corresponds to one store in either New Jersey or eastern Pennsylvania.</p>
<p>The original study uses full-time-equivalent employment (FTE), defined as the number of full-time employees plus the number of managers plus one-half of the number of part-time employees.</p>
<p>I follow the original replication logic and construct the same core variables used for the requested tables.</p>
<p>The data contain 410 restaurants in total.</p>
</section>
<section id="replication-of-selected-results-from-table-2" class="level3">
<h3 class="anchored" data-anchor-id="replication-of-selected-results-from-table-2">Replication of Selected Results from Table 2</h3>
<p>I begin with selected descriptive statistics from Table 2. These numbers are useful because they show whether the two states looked broadly comparable before the policy change and how wages and employment moved afterward.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Selected replication of Table 2</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">state_name</th>
<th style="text-align: right;">Company-owned</th>
<th style="text-align: right;">FTE employment (wave 1)</th>
<th style="text-align: right;">Fraction full-time</th>
<th style="text-align: right;">Starting wage (wave 1)</th>
<th style="text-align: right;">Meal price (wave 1)</th>
<th style="text-align: right;">Hours open (wave 1)</th>
<th style="text-align: right;">FTE employment (wave 2)</th>
<th style="text-align: right;">Starting wage (wave 2)</th>
<th style="text-align: right;">Meal price (wave 2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New Jersey</td>
<td style="text-align: right;">0.341</td>
<td style="text-align: right;">20.439</td>
<td style="text-align: right;">0.328</td>
<td style="text-align: right;">4.612</td>
<td style="text-align: right;">3.351</td>
<td style="text-align: right;">14.418</td>
<td style="text-align: right;">21.027</td>
<td style="text-align: right;">5.081</td>
<td style="text-align: right;">3.415</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: right;">0.354</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;">4.630</td>
<td style="text-align: right;">3.042</td>
<td style="text-align: right;">14.525</td>
<td style="text-align: right;">21.166</td>
<td style="text-align: right;">4.617</td>
<td style="text-align: right;">3.027</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These results are consistent with the main descriptive patterns in the paper. First, average starting wages in wave 1 are very similar across the two states, which is important because it suggests that the comparison is not being driven by a very different pre-policy wage environment. Second, average starting wages rise sharply in New Jersey by wave 2, which is exactly what should happen if the policy change was binding. Third, employment levels do not show any obvious collapse in New Jersey after the increase. That descriptive pattern already hints that the standard prediction of a large negative employment effect may not hold in this sample.</p>
</section>
<section id="replication-of-table-3-the-9-requested-numbers" class="level3">
<h3 class="anchored" data-anchor-id="replication-of-table-3-the-9-requested-numbers">Replication of Table 3: The 9 Requested Numbers</h3>
<p>The assignment specifically asks for the 9 numbers in Table 3, rows 1–3 and columns 1–3. I interpret these as the average FTE employment in February 1992, the average FTE employment in November 1992, and the change in FTE employment, each shown for New Jersey, Pennsylvania, and the New Jersey minus Pennsylvania difference.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Replication of Table 3, rows 1–3 and columns 1–3</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Row</th>
<th style="text-align: right;">New Jersey</th>
<th style="text-align: right;">Pennsylvania</th>
<th style="text-align: right;">NJ - PA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FTE employment in February 1992</td>
<td style="text-align: right;">20.439</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;">-2.892</td>
</tr>
<tr class="even">
<td style="text-align: left;">FTE employment in November 1992</td>
<td style="text-align: right;">21.027</td>
<td style="text-align: right;">21.166</td>
<td style="text-align: right;">-0.138</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Change in FTE employment</td>
<td style="text-align: right;">0.467</td>
<td style="text-align: right;">-2.283</td>
<td style="text-align: right;">2.750</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The most important quantity in this table is the difference-in-differences estimate in the third row and third column. That number is the change in New Jersey minus the change in Pennsylvania. In my replication, that estimate is 2.75. The sign is positive rather than negative.</p>
<p>This is the key statistical finding of the paper. Employment does not fall in New Jersey relative to Pennsylvania after the minimum-wage increase. If anything, the simple difference-in-differences estimate suggests that New Jersey employment performed slightly better over this period. That does not mean the policy necessarily raised employment in a broad structural sense, but it does mean the data do not support the simple claim that the higher minimum wage reduced fast-food employment in this case.</p>
<p>A useful way to read Table 3 is step by step. Before the policy, Pennsylvania stores had somewhat higher average FTE employment than New Jersey stores. By the second wave, that gap narrows. The reason is not that New Jersey employment collapses; instead, employment in Pennsylvania declines more over the same period. That is exactly why the difference-in-differences estimate turns positive.</p>
</section>
<section id="replication-of-table-4-column-i" class="level3">
<h3 class="anchored" data-anchor-id="replication-of-table-4-column-i">Replication of Table 4, Column (i)</h3>
<p>Table 4 moves from descriptive comparisons to regression-based evidence. The original replication code uses a subset of stores with valid second-wave wage information, plus stores that permanently closed. I follow that same rule and estimate Table 4 column (i) by regressing the change in employment on the wage-gap measure.</p>
<p>The <code>gap</code> variable captures how far a store’s initial wage was below the new minimum. Intuitively, stores with a larger gap were more exposed to the policy change and should have faced larger labor-cost increases.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Replication of Table 4, column (i)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.576</td>
<td style="text-align: right;">0.697</td>
<td style="text-align: right;">-2.263</td>
<td style="text-align: right;">0.024</td>
</tr>
<tr class="even">
<td style="text-align: left;">gap</td>
<td style="text-align: right;">15.653</td>
<td style="text-align: right;">6.080</td>
<td style="text-align: right;">2.574</td>
<td style="text-align: right;">0.010</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The coefficient on <code>gap</code> is 15.653. This coefficient is positive. In other words, stores that were more affected by the minimum-wage increase do not show larger employment declines. That is again inconsistent with the simplest competitive model prediction.</p>
<p>This regression result strengthens the interpretation from Table 3. Table 3 compares average employment changes across states. Table 4 adds variation in how exposed individual stores were to the policy. Both pieces of evidence point in the same direction: more exposed stores did not experience systematically worse employment outcomes in this data set.</p>
</section>
<section id="what-the-replication-suggests" class="level3">
<h3 class="anchored" data-anchor-id="what-the-replication-suggests">What the Replication Suggests</h3>
<p>Taken together, the replicated results tell a coherent story. Descriptive statistics show a clear wage increase in New Jersey after the policy. The simple difference-in-differences estimate from Table 3 is positive. The wage-gap regression in Table 4 column (i) is also positive. Across all three pieces of evidence, I do not find support for the claim that the 1992 New Jersey minimum-wage increase reduced fast-food employment in this sample.</p>
</section>
</section>
<section id="something-additional" class="level2">
<h2 class="anchored" data-anchor-id="something-additional">Something Additional</h2>
<section id="a-graphical-presentation-of-employment-changes" class="level3">
<h3 class="anchored" data-anchor-id="a-graphical-presentation-of-employment-changes">A Graphical Presentation of Employment Changes</h3>
<p>As an additional analysis, I present the employment change graphically. This translates one of the paper’s table-based results into a visual comparison.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure makes the main finding easier to see than the table alone. Mean employment change is slightly positive in New Jersey and clearly negative in Pennsylvania. Visually, that implies a positive difference-in-differences estimate. Presenting the result this way is helpful because the central substantive point of the paper is comparative: what matters is not the level in one state by itself, but how employment moved in New Jersey relative to the comparison group.</p>
</section>
<section id="why-difference-in-differences-supports-a-causal-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="why-difference-in-differences-supports-a-causal-interpretation">Why Difference-in-Differences Supports a Causal Interpretation</h3>
<p>The main reason this paper is so influential is not just the result, but the research design. A simple before-and-after comparison in New Jersey would be weak because many other things might have changed between February and November 1992. Employment could have moved because of macroeconomic trends, demand changes, or regional shocks unrelated to the minimum wage.</p>
<p>Difference-in-differences improves on that by using Pennsylvania as a comparison group. The identifying idea is that Pennsylvania captures the time trend that would have affected New Jersey even without the policy. When I subtract the Pennsylvania change from the New Jersey change, I remove common shocks that affected both states during the same period.</p>
<p>The key assumption is the parallel trends assumption: absent the policy change, employment in New Jersey and Pennsylvania would have evolved similarly on average. This assumption is not directly testable with only two periods, but it becomes more plausible because the two states are geographically close, observed over the same time window, and operate in the same industry. In that sense, Pennsylvania is a much more credible counterfactual for New Jersey than a distant or unrelated labor market would be.</p>
<p>This does not make the design perfect. The two states may still differ in ways that matter, and any causal claim depends on the quality of the comparison group. Still, difference-in-differences is much stronger than a pure before-and-after comparison, which is why Card and Krueger’s paper became such a foundational example in empirical economics.</p>
</section>
<section id="why-my-results-may-not-match-the-paper-perfectly" class="level3">
<h3 class="anchored" data-anchor-id="why-my-results-may-not-match-the-paper-perfectly">Why My Results May Not Match the Paper Perfectly</h3>
<p>Replication files often reproduce the main point estimates closely while leaving small differences due to coding choices, treatment of missing data, or formatting decisions. In this case, my goal is to match the substantive patterns emphasized in the paper: wages rise in New Jersey, the simple DID estimate is not negative, and the regression evidence in Table 4 column (i) does not support strong employment losses.</p>
<p>Even if some reported numbers differ slightly from the published table, the overall message remains the same. That is what matters most for this assignment: accurately reconstructing the empirical logic and showing that the main conclusion survives replication.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This post replicated selected findings from Card and Krueger (1994) using the public replication files. I reproduced selected descriptive statistics from Table 2, the 9 requested numbers from Table 3, and Table 4 column (i). I also added a graphical comparison of employment changes and explained why the difference-in-differences design supports a causal interpretation.</p>
<p>Overall, the replication supports the central conclusion of the paper. The New Jersey minimum-wage increase clearly raised starting wages, but I do not find evidence that it reduced fast-food employment in this sample. Both the simple difference-in-differences estimate and the regression evidence from Table 4 column (i) point away from a negative employment effect.</p>
<p>More broadly, this replication shows why the paper remains so important. It does not just report a surprising result; it demonstrates how a relatively simple quasi-experimental design can challenge a strong theoretical prediction using real-world data.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>